name: "write-service"
replicaCount: 1

images:
  PullSecrets: 
    name: kartoffelreg
  repository: rabazhub.azurecr.io/values-test
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000

# volume:
#   -name:
#    mountPath:
#    type:
#    claimName:

config:
  configmaps: 
    name: write-service

ingress:
  enabled: true
  hosts:
  - host: test-cd.branch-yesodot.org
    paths:
      - path: /message
        service: testname
        port: "3000"
  
